### ISSUE TITLE
Post about Bioconductor

### ISSUE THREAD

**Issue by maelle** [r-hub/blog#18]
Not well developed.

- Bioconductor. Maybe support by R-hub if it improves; in any case description of release cycles, review process etc., since it is an interesting system.

- why and how to setup a CRAN mirror? Ask a few maintainers of CRAN mirrors about their motivation and experience.

- Solaris, why does CRAN use it (link to Uwe Ligges' useR! 2017 keynote), why is it so complicated to maintain the corresponding platform.

**Comment by gaborcsardi** [comment]
My opinion:

> Bioconductor

Yes! Support is improving soon, I wrote the code that well get into remotes very soon. It is already in pkgcache: https://github.com/r-lib/pkgcache/pull/24

> why and how to setup a CRAN mirror?

Probably no. Mirrors are, well, silly. Content should be distributed via a CDN nowadays, not mirrors.

> Solaris.

I don't know. This is possibly very niche. Although I guess all maintainers with compiled code are potentially affected.

**Comment by maelle** [comment]
Thanks, and good news about Bioconductor remotes code!

**Comment by maelle** [comment]
Reg Bioconductor, there is at least one long issue thread in rhub issue tracker.

I was thinking a plot representing the overlap between R-devel/R-release and Bionconductor devel/release over time would be great (to illustrate how Bioconductor doesn't really support R-devel part of the year). The same thing can be explained with text but a plot would be cool. And it would use rversions.

**Comment by maelle** [comment]
https://bioconductor.org/config.yaml

**Comment by maelle** [comment]
Important/interesting points about Bioconductor

* Its support on R-hub, what to know
* "Bioconductor has a review process"
* "All Bioconductor packages have vignettes" (which is due to the item before, precise guidelines http://bioconductor.org/developers/package-guidelines/)
* "Bioconductor has a release schedule"
* "Bioconductor has its installer package"
* "But you can install Bioconductor packages without it" (setRepositories(), but less recommended than the installer package)
* "CRAN and Bioconductor ecosystems are intertwined" https://twitter.com/henrikbengtsson/status/1230902107756060673

**Comment by maelle** [comment]
On Travis

* Bioc devel -> R devel, Bioc release -> R release https://github.com/travis-ci/travis-build/blob/533dbbf39b8a5f7bf335bd448e521ae5cb781318/lib/travis/build/script/r.rb#L601-L604

* Installation done using Bioconductor's own tools https://github.com/travis-ci/travis-build/blob/533dbbf39b8a5f7bf335bd448e521ae5cb781318/lib/travis/build/script/r.rb#L419

* Bioccheck installed and used depending on the config https://github.com/travis-ci/travis-build/blob/533dbbf39b8a5f7bf335bd448e521ae5cb781318/lib/travis/build/script/r.rb#L250 E.g. https://github.com/nkurzaw/Rtpca/blob/c8b1ad5cbb554ba613e684108440863d853b432c/.travis.yml and Travis log https://travis-ci.org/nkurzaw/Rtpca

**Comment by maelle** [comment]
https://twitter.com/Lluis_Rev/status/1261277734690529281 & https://twitter.com/henrikbengtsson/status/708492026698797056
