### ISSUE TITLE
Idea: add link to documentation and build into the blog post navbar

### ISSUE THREAD

**Issue by cderv** [r-hub/blog#26]
Looking for the documentation website, from a google search I arrive through the Rhub blog. 

And I was expecting to find more link in the navbar to what is presented in about.md like 

* A link to the documentation 
* A link to the builder

What about adding these in `config.toml` to add direct link to these two important ressources ?

**Comment by maelle** [comment]
Thanks for this excellent suggestion! The whole blog theme should be overhauled in the next months, we'll make sure the websites are well cross-linked (maybe I made that word up).

**Comment by maelle** [comment]
@cderv now the footer features many links :tada:
