### ISSUE TITLE
internal vs external functions

### ISSUE THREAD

**Issue by maelle** [r-hub/blog#32]
More aimed at folks new to package development.

What is an internal function?
Why not to export all functions?
How to document internal functions (NoRd,keyword internal)?
Whether to test them?

Synonyms.
* Internal, unexported, helper
* External, exported, user-facing

In a few packages (R-hub packages), count the number of exported functions vs not exported functions, maybe count use of internal functions, and the ones that are similar between packages. But not too much, link to https://rud.is/b/2018/04/08/dissecting-r-package-utility-belts/

Links
* regarding helper functions (creating them vs importing them) https://resources.rstudio.com/rstudio-conf-2019/it-depends-a-dialog-about-dependencies
* probably r-pkgs

**Comment by maelle** [comment]
https://github.com/lorenzwalthert/parsesum

**Comment by gaborcsardi** [comment]
https://github.com/r-lib/pkgapi ?

**Comment by maelle** [comment]
very cool! and if it doesn't work I'll complain :grin:

**Comment by maelle** [comment]
How to find duplicate code to write helper functions for: https://cran.r-project.org/web/packages/dupree/index.html, other tools?

**Comment by maelle** [comment]
How to document internal functions, https://community.rstudio.com/t/keywords-internal-vs-nord/35119

**Comment by maelle** [comment]
add a visualization (and quote https://twitter.com/hugomflavio/status/1189450186826960896)

add a conclusion
