### ISSUE TITLE
blog post about rversions

### ISSUE THREAD

**Issue by maelle** [r-hub/blog#4]
- if new CRAN version, release post. (btw https://github.com/mrc-ide/provisionr/blob/0c1f30a4bcf350a9e354a23535c4df71b51dea4a/R/r_version.R#L34 is waiting for a CRAN release)
- is it used by R-hub if so how?
- mention reverse dependencies. 
    - One of the 2 reverse Suggests listed on CRAN might not use the package at all actually; the other one is `devtools` where it is used in [`dr_devtools()`](https://devtools.r-lib.org/reference/dr_devtools.html) to compare the installed R version to the current R release version.
    - There's at least one package on GitHub, https://github.com/mrc-ide/provisionr that _imports_ `rversions`. In `check_r_version()` `rversions` is used. The function checks and coerces something into an R version.

**Comment by gaborcsardi** [comment]
IDK if rversions is important enough to write a blog post TBH.

**Comment by maelle** [comment]
it'll be a short one :wink:

**Comment by maelle** [comment]
Other items

* Where the info about R versions comes from

* Plot the frequency of updates over time (and mention how it changed, while Bioconductor release schedule didn't change).

**Comment by gaborcsardi** [comment]
OK, then. :) 

- r-appveyor uses it (well, the web service) to determine what versions r-release and r-oldrel are:
https://github.com/krlmlr/r-appveyor/blob/master/scripts/appveyor-tool.ps1#L77-L87

- R-hub uses it to do the same:
https://github.com/r-hub/solarischeck/blob/d3edc6077f52081a53b2ed8b9ec40e17176fdb43/run.sh#L105
https://github.com/r-hub/macoscheck/blob/846f87d1ad1c4b4aeb283a986e084913f203879f/run.sh#L160
https://github.com/r-hub/wincheck/blob/591ea8d9a28cd5044c063e88f46ef0507fa16fc7/run.ps1#L114

**Comment by maelle** [comment]
Thanks! :ok_hand:

**Comment by gaborcsardi** [comment]
> Where the info about R versions comes from

- r-versions are coming from SVN tags:
https://github.com/metacran/rversions/blob/master/R/rversions.R#L79
- r-release is the latest SVN tag
- r-oldrel is the latest of the previous minor version
- r-release-tarball is the latest SVN tag that has a corresponding tar.gz to download
- windows, macos are the same: latest svn tag that has a file to download

**Comment by gaborcsardi** [comment]
out windows install script uses it as well, to decide what versions of R to install: https://github.com/r-hub/rhub-server/blob/master/jenkins/scripts/windows-2008-setup.ps1#L74-L79

**Comment by maelle** [comment]
see, a very niche package, but an useful one :-)
