### ISSUE TITLE
Generate code for a package

### ISSUE THREAD

**Issue by maelle** [r-hub/blog#41]
* Generating code (or even just scaffolding it)

* Particular case when wanting to do that from the package itself cf https://twitter.com/MilesMcBain/status/1199451518090395649?s=20 by @milesmcbain

**Comment by maelle** [comment]
https://github.com/ropenscilabs/icon

**Comment by maelle** [comment]
https://reproducible-builds.org/news/2017/05/03/reproduciing-r-packages/

**Comment by maelle** [comment]
Cases where you might want to generate code for a package automatically

* web API (to support new endpoints/the whole thing, or even several APIs cf Googel case). Either use the scaffoling as a starting point or really build a package?

* Aliases for things that are clearly similar, cf icons.

* Docs cf xaringanthemer.

**Comment by maelle** [comment]
Packages are just a collection of R scripts and man files. The easiest way to generate code (& docs) for a package is generating the R scripts and then running document() etc like xaringanthemer. https://github.com/gadenbuie/xaringanthemer/blob/master/make.R

icons approach is a bit different. At build time the functions are created. use of `@exportPattern`

**Comment by maelle** [comment]
in icons there are two things that happen, the function generation at built time and the documenting that's before then (using `@evalRd` in particular). quite interesting

**Comment by maelle** [comment]
in the conclusion, ask for further examples + encourage readers to create little play packages to explore ideas.

**Comment by maelle** [comment]
Not in scope for this post: packages exporting function factories for the user to use.

**Comment by maelle** [comment]
civis https://twitter.com/patr1ck_mil/status/1199456574105882625?s=20

https://github.com/civisanalytics/civis-r#updating (so two installation modes, from source that'll use the generator, the other won't)

Look in WRE what's written about configure scripts.

"If your configure script needs auxiliary files, it is recommended that you ship them in a tools directory (as R itself does). "

"If your package has a configure script, provide a configure.win script to be used on Windows"

**Comment by maelle** [comment]
In https://github.com/coolbutuseless/minicss/blob/fe378f6e040405e51fb07cb74fd2f0bac8a85b26/R/prop_transform.R#L99
https://twitter.com/coolbutuseless/status/1199458806092034049?s=20
there's a list of methods and then a for loop create one method for each.

**Comment by maelle** [comment]
the code generation done by a special package https://github.com/vegawidget/vlbuildr#building https://twitter.com/ijlyttle/status/1199454056638537728?s=20

**Comment by maelle** [comment]
I'd need to find an example for https://twitter.com/hadleywickham/status/1199493296986288128?s=20 (actually onLoad would be an interesting post topic...)

**Comment by maelle** [comment]
inst/build.R https://twitter.com/henrikbengtsson/status/1199460876404871168?s=20

**Comment by maelle** [comment]
wisegroup itself https://github.com/MilesMcBain/wisegroup/blob/master/build.R

**Comment by maelle** [comment]
XML spec https://github.com/cboettig/build.eml/blob/master/data-raw/create-functions.R

**Comment by maelle** [comment]
at runtime https://twitter.com/alandipert/status/1199456564442062848?s=20

**Comment by maelle** [comment]
stevedore generates code on the fly https://github.com/richfitz/stevedore (sort of)

**Comment by maelle** [comment]
Generating vs scaffolding.
* Scaffolding: where and how is more of a project management problem.
* Generating: when? 
	* Once in a while to update R scripts and their docs? (xaringanthemer, wisegroup, redux, eml.build, crrri used to) In that case does the machinery live inside the package or in another package/external script? (external package: vlbuild)
    * At build time (icon, civis when installed from source via the configure scripts)
    * Later. chromote, stevedore.

**Comment by maelle** [comment]
Generating the package code vs writing a package that helps generate code.

**Comment by maelle** [comment]
https://en.wikipedia.org/wiki/Automatic_programming

**Comment by maelle** [comment]
State that code is generated as a string, and written to disk in some workflows, eval/parsed in other workflows.

**Comment by richfitz** [comment]
> State that code is generated as a string, and written to disk in some workflows, eval/parsed in other workflows.

3rd option is not going through the text representation at all and using things like `as.function` and `call`/`as.call` to build up functions and expressions directly

**Comment by maelle** [comment]
Thank you, I'll explore that!

**Comment by maelle** [comment]
https://docs.google.com/presentation/d/e/2PACX-1vRUDiM3DaPjYP5b1BafSraf8GWwJk_jy6YV_l9lZgeBVwKDSfqiHcTn8M-Qm-6U7frMX7SLqQthJxah/pub?start=false&loop=false&delayms=3000&slide=id.g6e3ba3f0ad_0_5

**Comment by maelle** [comment]
Draft PR #67

**Comment by maelle** [comment]
Rcpp attribute creation
