### ISSUE TITLE
Possible guest post about fixing a CRAN issue

### ISSUE THREAD

**Issue by maelle** [r-hub/blog#46]
Per https://github.com/r-hub/rhub/issues/322#issuecomment-563947253

Cc @jromanowska

**Comment by jromanowska** [comment]
Hi, I have some days to write the post - could you give me some instructions on what to use and where to submit it?

**Comment by maelle** [comment]
Yay! 🎉 I'll give more info later today but what you'll need to submit is a Markdown file like https://github.com/r-hub/blog/blob/master/content/post/2019-04-08-rhub-release.md via a pull request.

Do you think you'll write in Markdwon directly or do you want to knit from R Markdown?

**Comment by maelle** [comment]
I've opened a [draft PR](https://github.com/r-hub/blog/pull/50) so you might see how the PR will look like. [Post preview](https://deploy-preview-50--admiring-allen-9a00b2.netlify.com/2019/12/20/informative-title/). You're the first guest post writer so I apologize in advance for any problem and I welcome any question/feedback!

* You can write the post in a separate project and folder using [the template](https://github.com/r-hub/blog/blob/examplepost/content/post/2019-12-20-informative-title/index.Rmd). It should be named index.Rmd. Knitting it will produce both index.md, and index.html that will be ignored in your PR later. At the end of this step you'll have a folder with index.Rmd, index.md, images, (and index.html). You can also directly use the index.md template as you prefer.

* Then you can clone this repo, and create a branch from master. Insert the folder from the previous step under post/, with a name that's YYYY-MM-DD-slug. Push and open a pull request.

* I'll make comments and edit suggestions in the PR. We can edit the publication date based on progress, no pressure.

As you see we don't have author pages yet hence my template's encouraging your adding info at the beginning and at the end of the post for readers to easily connect with you. You can replace "Julia" with "Dr Julia Romanowska", I've just written Julia, no first name obligation obviously.

Thank you! I'm looking forward to reading your post!

**Comment by maelle** [comment]
I forgot to add that if you're not at ease with the PR making, I can help with that!

**Comment by maelle** [comment]
And reg content, here are a few possible questions
* What does your package do? (briefly, with a link to its homepage and/or source code repo)
* How/when did you notice the CRAN problem? (btw we have two relevant posts on the blog, [How to handle CRAN checks with help from R-hub](https://blog.r-hub.io/2019/04/25/r-devel-linux-x86-64-debian-clang/) and [Overview of the CRAN checks API](https://blog.r-hub.io/2019/06/10/cran-checks-api/).
* How did you reproduce the CRAN error? What problems did you encounter?
* How did you _solve_ the CRAN error? Has the package been updated on CRAN or is it in progress?
* What resources would you recommend/what lessons have you learnt?

**Comment by jromanowska** [comment]
Great, thank you for the explanations! I'm gonna probably use Rmarkdown and knit from this. I haven't done any pull requests before, but I'm keen to try. Ok, I'll see how far I can get before I'm stuck ;)

**Comment by maelle** [comment]
Cool!

When you're at the PR stage of course I'll help but you might also find [this vignette and the related tools](https://usethis.r-lib.org/articles/articles/pr-functions.html) helpful.

**Comment by jromanowska** [comment]
>     * Insert the folder from the previous step under post/, with a name that's YYYY-MM-DD-slug.

Did you mean to insert it under "content"? I can't see a "post" folder in the main folder.

**Comment by maelle** [comment]
Right, sorry, yes, content/post/ as in the PR.

**Comment by jromanowska** [comment]
Hi and Happy New Year!
I've tried pushing my new branch to github repo, but I don't seem to have access to push changes... is this true? Or am I doing something wrong?

```
> home:post$ git push --set-upstream origin jromanowska-guest-post
ERROR: Permission to r-hub/blog.git denied to jromanowska.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by maelle** [comment]
Hi, happy new year! Yes, you need to fork the repo first and create the branch in the fork, sorry for being unclear. I'd recommend first making a copy of your local folder to not lose your work.

**Comment by jromanowska** [comment]
Ok, now I think I've managed to do that. Sorry - it's my first time contributing to somebody else's repo! :)

**Comment by maelle** [comment]
No problem at all!

**Comment by maelle** [comment]
fixed in #46

**Comment by jromanowska** [comment]
Hi again :)
@HenrikBengtsson gave me some tips regarding the blog post and I would like to update it - should I just add some text at the bottom or re-write the post?

**Comment by maelle** [comment]
@jromanowska you can update the post (make a PR editing it), depending on the number of edits you can add a note in italic at the beginning "edited on <date> thanks to comments by Henrik Bengtsson". This way future readers only see the updated version?

**Comment by jromanowska** [comment]
Yes, great!
