### ISSUE TITLE
Suggests is not You might also like

### ISSUE THREAD

**Issue by maelle** [r-hub/blog#48]
* Run a script to find unneeded dependencies over many CRAN repos (using `attachment`) 

* What Suggests is for

* Is Suggests ok for development dependencies (mention [ThinkR approach](https://github.com/ThinkR-open/attachment/blob/master/inst/dependencies.R), @jeroen's suggestion https://github.com/r-lib/remotes/issues/459 Servers, and human contributors.

**Comment by maelle** [comment]
https://twitter.com/eddelbuettel/status/1217070876035899397?s=20

**Comment by gaborcsardi** [comment]
This is a twist: https://cran.rstudio.com/web/checks/check_results_callr.html

<img width="309" alt="Screen Shot 2020-01-23 at 11 47 01" src="https://user-images.githubusercontent.com/660288/72982093-359d0500-3dd6-11ea-9ff9-210f910f0761.png">

**Comment by maelle** [comment]
:open_mouth:

**Comment by maelle** [comment]
- Site/Needs/blabla
- xdref NOTE, is it really problematic.
