### ISSUE TITLE
Guest post about packageRanks

### ISSUE THREAD

**Issue by maelle** [r-hub/blog#49]
By @lindbrook cf https://github.com/lindbrook/packageRank/issues/4

Reg length the [post about rversions](https://blog.r-hub.io/2019/04/15/rversions-1-1-0/) has a 4min reading time and the [post about cranlogs](https://blog.r-hub.io/2019/05/02/cranlogs-2-1-1/) has a 6min reading time, which I find good. It means 880-1320 words as a ballpark figure. 

Reg timing, ping me again when you're ready to start working on it, no hurry and absolutely no pressure!

I am thinking of the post as a way to describe the motivation and use case(s) in practice of your package as well as to make readers curious to read more in your package docs. Compared to the README, I'd be e.g. curious to read how you got the idea to start the package, and how it's been useful in your work (or was it just a project out of curiosity for the numbers).

Note: At the moment the R-hub blog doesn't show authors of posts but this will change + for a guest post we'd add a sentence at the beginning of the post to be sure there are links to your online presence.

**Comment by lindbrook** [comment]
Question of attribution (fact checking): are the download logs of RStudio's CRAN mirror an r-hub or an RStudio project/product? I got the impression that @gaborcsardi has/had a hand in the script that created the logs at http://cran-logs.rstudio.com/

**Comment by maelle** [comment]
I'll let @gaborcsardi answer that.

When you're ready to submit your post (no hurry, but since I haven't stored instructions somewhere central yet, I'll put them here for when you need them) I've made an example PR for another guest post: https://github.com/r-hub/blog/pull/50/files You'd need to fork this repo first.

* You can write the post in a separate project and folder using [the template](https://github.com/r-hub/blog/blob/examplepost/content/post/2019-12-20-informative-title/index.Rmd). It should be named index.Rmd. Knitting it will produce both index.md, and index.html that will be ignored in your PR later. At the end of this step you'll have a folder with index.Rmd, index.md, images, (and index.html). You can also directly use the index.md template as you prefer.

* Then you can fork + clone this repo, and create a branch from master. Insert the folder from the previous step under content/post/, with a name that's YYYY-MM-DD-slug. Push and open a pull request.

* I'll make comments and edit suggestions in the PR. We can edit the publication date based on progress, no pressure at that stage either.

**Comment by gaborcsardi** [comment]
> Question of attribution (fact checking): are the download logs of RStudio's CRAN mirror an r-hub or an RStudio project/product? I got the impression that @gaborcsardi has/had a hand in the script that created the logs at http://cran-logs.rstudio.com

The logs on RStudio's CRAN mirror is an RStudio project. Hadley wrote the script that processes the web server logs and makes the summary available daily.

The cranlogs package and the DB behind is is an R-hub project.

**Comment by lindbrook** [comment]
I have some external data that I'd like to use in my post. Other than including them in my package, do you have a preferred way to do this? If a package is the way to go, is availability on GitHub sufficient or do you prefer it to be on CRAN? I'm pretty close to pushing a new version to CRAN.

**Comment by maelle** [comment]
No we don't have any guidance regarding this. It's great if the data is publicly available and the interested readers can get it easily, so its being on GitHub is enough. Thanks for asking!

**Comment by lindbrook** [comment]
I seem to be having problems with graphs. I started with the template but never managed to get them to appear in the html. So I went back to the template itself. When I knit the template, the "chunkname" plot doesn't appear in the html preview. You just get: 

{{
}}

Maybe some kind of path problem?

**Comment by maelle** [comment]
You mean the html preview of the Rmd? Yeah the Rmd template is so that you'll see the images in the Hugo preview thanks to the md you get from knitting the Rmd. 

If you want the html preview to feature images you can comment the code in the setup chunk before knitting (code that defines the Hugo plot hook), but before submitting your post (PR with Rmd, md, images but no html) uncomment it and knit again.

Note that I am often offline this week so might be slow to respond.

**Comment by maelle** [comment]
(And thanks for the feedback + sorry for this being unclear! You're making the life of future guest authors easier but not yours 😢)

**Comment by lindbrook** [comment]
I see. Now it's working. (No worries)

**Comment by lindbrook** [comment]
How can I check what the Hugo flavored output looks like?

**Comment by maelle** [comment]
First you'll need to add index.Rmd, index.md and images in a folder (in a branch of the fork of this repo) like in the example PR.

Then either install Hugo and run hugo server in the blog folder, or open a draft PR because that will get a preview.

Logging off now, I can help more tomorrow.

**Comment by lindbrook** [comment]
I'm getting ready to push a draft of the blog post. It's twice as long as you'd like. The first half is an introduction to 'packageRank'. The second half is an overview of the positive bias/inflation of download counts. If one or the other seems more interesting/appropriate, I can just push that part. If you want to see both parts before making a decision, I can push the whole thing.

**Comment by maelle** [comment]
Yes please open a PR with both parts! Thank you!

**Comment by lindbrook** [comment]
Just tried to upload the draft. Please use 'packageRank'  v0.3.0.9042 on GitHub.
