### ISSUE TITLE
docs: no reverse dependency checker

### ISSUE THREAD

**Issue by helix123** [r-hub/blog#55]
Can we have a little addition in the docs what r-hub (the builder) is not: a reverse dependency checker. And maybe a pointer how to check reverse dependencies.

(I am thinking of this section: https://docs.r-hub.io/#intro)

**Comment by maelle** [comment]
Not good enough for doing what?

**Comment by gaborcsardi** [comment]
for blogging about it

**Comment by helix123** [comment]
@maelle Thank you. For my understanding of your suggestion how to check reverse dependency with r-hub: The way you lay out is on a per (reverse dependency) package base? I.e. if my package has 20 reverse dependencies I would need to run that process 20 times, once for each reverse dependency?

**Comment by maelle** [comment]
Yes but I'm not sure you should, if things work locally? @gaborcsardi do you ever check reverse dependencies somewhere else than locally?

**Comment by gaborcsardi** [comment]
Not that I remember. I don't think there is good infrastructure for non-local revdep checks.

**Comment by maelle** [comment]
And is there any good general reason for non-local revdep checks or in general can one trust local results unless there's some special case?

**Comment by gaborcsardi** [comment]
Well, if we could run all of them in parallel, that would be good....

**Comment by helix123** [comment]
So, this discussion emphasizes my initial point: Could you add to the webpage that r-hub is not meant for reverse dependency checks?

**Comment by maelle** [comment]
Added to docs https://docs.r-hub.io/#revdeps

Thanks!

**Comment by helix123** [comment]
Thank you, but one link is broken. I believe you meant to link to http://www.markvanderloo.eu/yaRb/2019/04/26/checking-reverse-dependencies-the-tiny-way/

**Comment by maelle** [comment]
Good catch :woman_facepalming: Thank you!
