### ISSUE TITLE
How to save user preferences

### ISSUE THREAD

**Issue by maelle** [r-hub/blog#73]
Excellent R-pkg-devel thread https://stat.ethz.ch/pipermail/r-package-devel/2020q1/004854.html

* Startup files (including options in .Rprofile), [pkg environment defined in onLoad](https://github.com/eddelbuettel/anytime/blob/caf5ae8f0824c212ac418eb3a1db3f95097153ed/R/init.R)

* `rappdirs` (which is what `rhub` uses!)

Look for rappdirs example.

**Comment by maelle** [comment]
https://twitter.com/henrikbengtsson/status/1233487759412809734

**Comment by gaborcsardi** [comment]
FWIW this has come up a bunch of times already on R-devel and R-pkg-devel: https://www.mail-archive.com/r-package-devel@r-project.org/msg02460.html

**Comment by maelle** [comment]
Cool, it makes the post topic very relevant.

**Comment by maelle** [comment]
Also to be mentioned: sometimes you can _guess_ user "preferences", e.g. with `whoami` you don't necessarily need the user to input their name preference.

**Comment by maelle** [comment]
One aspect is "package data", another "user identity"

I'm looking for best practice in other languages/frameworks, maybe a table comparing different storage locations

https://developer.android.com/guide/topics/data

https://developer.android.com/jetpack/docs/guide#best-practices "Persist as much relevant and fresh data as possible."

Reg whoami https://developer.android.com/training/id-auth/identify

**Comment by maelle** [comment]
Topics are actually

* Package data

* User preferences (.Renviron, .Rprofile, other things)

* User identity (what you can guess with whoami, which is overlapping with .Renviron for part of whoami functionality e.g. GitHub username)

**Comment by maelle** [comment]
general goal = saving time (download time, setup time), while respecting the rules.

**Comment by maelle** [comment]
Backup of package data? https://developer.android.com/guide/topics/data/backup I don't think it happens. But the docs of a function that caches results should probably mention it's caching data for next time.

**Comment by maelle** [comment]
For each functions of rappdirs find an example with GitHub search

**Comment by maelle** [comment]
user_data_dir https://github.com/jsta/nsws

**Comment by maelle** [comment]
https://cran.r-project.org/web/packages/hoardr/index.html
