### ISSUE TITLE
add writeup of where to get package binaries

### ISSUE THREAD

**Issue by maxheld83** [r-hub/blog#82]
as with #81 I'm always re-researching the whole package binary availability situation in all combinations of

- [ ] OS
- [ ] distros (for linux)
- [ ] R versions
- [ ] or generally, old package binaries

Between the (public?) RSPM binaries (for some distros), [Michael Rutters debian binaries](https://launchpad.net/~marutter/+archive/ubuntu/rrutter), sometime-late (?) CRAN macOS binaries and [renv](https://rstudio.github.io/renv/index.html)s semi-related local global pkg cache, there seems to be a lot to consider.

I'm not the greatest expert on compiled packages, because I've never myself *written* packages with any compiled code, but I have struggled with this from the other end.

Is there a good resource for this already?
if not, might this blog be a place for a writeup about this?

**Comment by maelle** [comment]
It sounds like a cool blog post topic indeed, I'll think about it, thank you!

**Comment by maelle** [comment]
Just to clarify, are you volunteering to write it? Otherwise I can write it, not an expert either, but always glad to research such things.

**Comment by maxheld83** [comment]
I ✋volunteer as (con)tribute 😄. 
(It's week 4 🙃).

Just wanted to make sure this would be a good platform for the topic and that I hadn't missed someone else's work on the subject.

**Comment by maelle** [comment]
Awesome! I always think of that movie when writing "I volunteer" :see_no_evil: 

Yes it's a good fit for the blog and I don't know of other write-ups either.

You could write it when you have time, no hurry. We don't really have contributing guidelines but an example PR https://github.com/r-hub/blog/pull/50 and I can answer further questions.

**Comment by maxheld83** [comment]
Just found this (recent) blog post by Colin which covers most everything: https://www.jumpingrivers.com/blog/faster-r-package-installation-rstudio/

**Comment by maelle** [comment]
ah, good, thanks!

**Comment by maelle** [comment]
If you want to write your own perspective (linking existing stuff) and add some aspects, a blog post would of course still be welcome.
